### ISSUE TITLE
We should be preventing normal users from logging in to the admin page.

### ISSUE THREAD

**Issue by nikdunn** [toastymmm/server#15]

**Comment by c650** [comment]
But non admins can log in on mobile. So how do we resolve that? User agent string?

**Comment by Cyral** [comment]
I can send a third parameter like "admin: true" for the login request. Any routes that need admin access, and the login route when the admin property is true, should only be accepted if the current user (fetched from the session DB) is an admin.

**Comment by nikdunn** [comment]
> But non admins can log in on mobile. So how do we resolve that? User agent string?

There's nothing to resolve. The server knows whether the user (whether mobile or web) is an admin. Certain APIs that are protected like (/users GET) will return 403 Forbidden if they aren't an admin.

Other APIs that require either an admin or the creator of the message will perform the necessary checks and either allow or disallow.

**Comment by c650** [comment]
Cool ok so nothing has to change?

**Comment by nikdunn** [comment]
Not that I can think of
