### ISSUE TITLE
Mobile user lacks ability to query message history

### ISSUE THREAD

**Issue by bpglaser** [toastymmm/server#18]
The "/messages/{userID}" endpoint obviously requires a userID to access. However, the mobile user currently has no way of obtaining the userID. Neither login nor register return it.

Possible solutions:
1. return the userID for login or register
2. add a "/messages/me" endpoint or similar to get the logged in user's history

**Comment by c650** [comment]
Okay I can throw together a /messages/me probably.

**Comment by c650** [comment]
https://github.com/toastymmm/server/pull/20 :wink: i literally codeblasted this in 8 minutes

**Comment by bpglaser** [comment]
You're the man now, dog!

**Comment by bpglaser** [comment]
@c650 Is this endpoint reflected in the swagger? I mean, I suppose that it doesn't need to be.

**Comment by c650** [comment]
Yeah it is.
