### ISSUE TITLE
Need a download link for the apk file

### ISSUE THREAD

**Issue by nikdunn** [toastymmm/server#23]

**Comment by bpglaser** [comment]
Do we need to host it ourselves? I think that a link to the GitHub releases page would suffice.

https://github.com/toastymmm/mobile/releases

**Comment by nikdunn** [comment]
Maybe we don't need to host it ourselves. Are we going to put a link to the github release in our slides, then?

**Comment by c650** [comment]
More than fine for early products.

**Comment by nikdunn** [comment]
Let's keep this issue open to track the requirement to create a release and add a link to the slides then.
