### ISSUE TITLE
Current userID set via cookies

### ISSUE THREAD

**Issue by bpglaser** [toastymmm/server#30]
Would it be possible to set the userID via cookies? That way I can use it to confirm who owns a message for modification.

**Comment by c650** [comment]
UserId is already stored in the session though.

**Comment by bpglaser** [comment]
Does sid have several components?

**Comment by c650** [comment]
It should, yeah

**Comment by bpglaser** [comment]
Oh. I assumed it was just a token string. I'll have to investigate.

**Comment by bpglaser** [comment]
This looks like the content of the string:

>s%3AOsM-5ZtHcHw6CCXamArH5SmeoJGlrQxp.MVq4zajBTyD44VsODeWRYWmFo0wIsNdXPjLYU%2BkaZo8

Any obvious place that it should be split? Or is it some special format that I need to parse. i.e. JWT

**Comment by nikdunn** [comment]
It is just a token string

Do you really want to SET the user id via cookies or was this to GET the user id in the cookie.

**Comment by bpglaser** [comment]
It looks like it is functional now
