### ISSUE TITLE
Mobile has no way of getting the username for a message

### ISSUE THREAD

**Issue by bpglaser** [toastymmm/server#32]
We need to either send the creator's username along with the message or create a /user/{userId} [GET] endpoint.

**Comment by c650** [comment]
Which endpoints need to be modified?

**Comment by bpglaser** [comment]
Any of the endpoints that return a Message object. 
/messages [GET]
/messages/me [GET]
/message/{id} [GET]
/favorites/me [GET]

I'm not sure about the others

**Comment by c650** [comment]
/favorites/me doesn't return message objects, only ID's, unless you want that changed also?

**Comment by bpglaser** [comment]
My bad, you're right. That one doesn't need to be modified then.

**Comment by bpglaser** [comment]
I am currently fetching the username for messages if they need to be displayed and are found to be lacking a username. Functional enough for me.
