### ISSUE TITLE
Deleting a favorite takes the wrong ID value

### ISSUE THREAD

**Issue by bpglaser** [toastymmm/server#33]
The /favorite/{id} [DELETE] endpoint uses the Favorite::_id field instead of the Message::_id. I can work around it by fetching the favorites before the DELETE but this seems wasteful to make two calls just to do the mapping. Can the delete endpoint use the Message::_id value instead? It seems more consistent since the /favorite/{id} [POST] endpoint uses the Message::_id.

**Comment by c650** [comment]
Oh lol. Yeah I guess that makes sense. In that case, I don't think that favorites even need their own id, then. I can re-work this in just a bit.

**Comment by bpglaser** [comment]
If we're going from the favorites page yes. However, the messages displayed on the map don't go through the favorites endpoint first. They come from messages.

**Comment by c650** [comment]
How do you even know that a message has already been favourited then?

**Comment by bpglaser** [comment]
When I actually go to the favorites page I query the favorites endpoint (since I might not have a local copy of favorites that are out of range).

**Comment by c650** [comment]
And if a user views a message nearby, how do you figure out if it's already been favorited?

**Comment by bpglaser** [comment]
I'm still doing a favorites call when I go to the detailed view. I suppose that I can cache the value but it would be more consistent if I could pass the Message::_id to the favorites [DELETE] endpoint.

**Comment by c650** [comment]
I think your implementation should grab the favorites on login and also update them locally, saving them in a data structure so that you know how to resolve each favorite to a specific message.

**Comment by bpglaser** [comment]
Yeah. I can do that instead.
