### ISSUE TITLE
Unable to report other users

### ISSUE THREAD

**Issue by bpglaser** [toastymmm/server#36]
Mobile user is currently unable to report messages of other users. The patch endpoint is restricted to one's own messages.

Steps to reproduce:
1. find another user's message
2. call patch to report
3. server returns 403

Expected behavior:
User is able to report other user's messages.

see: https://github.com/toastymmm/server/issues/22

**Comment by c650** [comment]
I will make a POST `/report/{id}`

**Comment by c650** [comment]
https://github.com/toastymmm/server/pull/37
